In [7]:
import numpy as np

def conv2d(inputs, kernels, padding, bias, stride):
    c, w, h = inputs.shape
    inputs = np.pad(inputs, ((0,0),(1,1),(1,1)))	## 可以直接用np.pad函数实现pad
    kernels_num, kernel_size = kernels.shape[0], kernels.shape[2]
    
    outputs = np.ones((kernels_num, (w-kernel_size+2*padding)//stride+1, (h-kernel_size+2*padding)//stride+1))
    for i in range(0, w-kernel_size+2*padding+1, stride):
        for j in range(0, h-kernel_size+2*padding+1, stride):
            outputs[:, i//stride, j//stride] = np.sum(np.multiply(kernels, inputs[:, i:i+kernel_size, j:j+kernel_size]), axis=(1,2,3)) + bias
    return outputs

inputs = np.ones((16,9,9))
kernels = np.ones((25,16,3,3))
bias = np.arange(1,kernels.shape[0]+1)
stride = 2
padding = 1
outputs = conv2d(inputs, kernels, padding, bias, stride)
print("input{}".format(inputs.shape))
print("kenerls{}, stride{}".format(kernels.shape, stride))
print("output{}".format(outputs.shape))
print(outputs)


(16, 9, 9)
(16, 11, 11)
input(16, 9, 9)
kenerls(25, 16, 3, 3), stride2
output(25, 5, 5)
[[[ 65.  97.  97.  97.  65.]
  [ 97. 145. 145. 145.  97.]
  [ 97. 145. 145. 145.  97.]
  [ 97. 145. 145. 145.  97.]
  [ 65.  97.  97.  97.  65.]]

 [[ 66.  98.  98.  98.  66.]
  [ 98. 146. 146. 146.  98.]
  [ 98. 146. 146. 146.  98.]
  [ 98. 146. 146. 146.  98.]
  [ 66.  98.  98.  98.  66.]]

 [[ 67.  99.  99.  99.  67.]
  [ 99. 147. 147. 147.  99.]
  [ 99. 147. 147. 147.  99.]
  [ 99. 147. 147. 147.  99.]
  [ 67.  99.  99.  99.  67.]]

 [[ 68. 100. 100. 100.  68.]
  [100. 148. 148. 148. 100.]
  [100. 148. 148. 148. 100.]
  [100. 148. 148. 148. 100.]
  [ 68. 100. 100. 100.  68.]]

 [[ 69. 101. 101. 101.  69.]
  [101. 149. 149. 149. 101.]
  [101. 149. 149. 149. 101.]
  [101. 149. 149. 149. 101.]
  [ 69. 101. 101. 101.  69.]]

 [[ 70. 102. 102. 102.  70.]
  [102. 150. 150. 150. 102.]
  [102. 150. 150. 150. 102.]
  [102. 150. 150. 150. 102.]
  [ 70. 102. 102. 102.  70.]]

 [[ 71. 103. 103. 103.  71.]
 